# Use new trusty images, should yield newer compilers and packages
dist: trusty
sudo: true
language: cpp

git:
  depth: 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - lcov
      - cmake
      - cmake-data

# before_install runs after matrix.addons.apt installation targets in the matrix
before_install:
  - export CTEST_OUTPUT_ON_FAILURE=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 50; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --config gcc; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --config g++; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --config gcov; fi
  - if [[ -x "${TRAVIS_BUILD_DIR}/ci/build_capnp.sh" ]]; then source ${TRAVIS_BUILD_DIR}/ci/build_capnp.sh; fi


# Build steps
script:
  - mkdir tmp
  - mv !(tmp) tmp # Move everything but tmp
  #- git clone https://github.com/MariaDB/server.git -b mariadb-10.2.7
  - wget https://downloads.mariadb.org/interstitial/mariadb-10.2.7/source/mariadb-10.2.7.tar.gz
  - tar xf mariadb-10.2.7.tar.gz
  - mv tmp mariadb-10.2.7/storage/crunch
  - cd mariadb-10.2.7
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release .. && make -j24
  - make test
